name: CI

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - 'feature/*'
      - 'bugfix/*'
      - 'hotfix/*'
      - 'release/*'

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: docker.datascience

jobs:
  build_data_science_image:
    name: Build Data Science Image
    runs-on: ubuntu-latest
    outputs:
      docker_version: ${{ steps.docker_version.outputs.version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get docker version
        id: docker_version
        run: |
          echo "version=$(git ls-files -s Dockerfile | awk '{print $2}' | cut -c1-16)" >> $GITHUB_OUTPUT

      - name: Check if image exists
        id: image_exists
        run: |
          response=$(docker manifest inspect ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME:${{ steps.docker_version.outputs.version }} > /dev/null ; echo $?)
          echo "image_exists=$(echo ${response})" >> $GITHUB_OUTPUT

      - name: Build docker image if it is not on registry
        if: ${{ steps.image_exists.outputs.image_exists == 1 }}
        run: make image

      - name: Login to Dockerhub
        if: ${{ steps.image_exists.outputs.image_exists == 1 }}
        uses: docker/login-action@v1
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image to Docker hub Registry
        if: ${{ steps.image_exists.outputs.image_exists == 1 }}
        run: |
          IMAGE_ID=${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          # Strip git ref prefix from version
          VERSION=$(git ls-files -s Dockerfile | awk '{print $2}' | cut -c1-16)

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          echo IMAGE_NAME=$IMAGE_NAME

          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME:$VERSION $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION

          docker tag $IMAGE_ID:$VERSION $IMAGE_ID:latest
          docker push $IMAGE_ID:latest

  build_variant_images:
    needs: build_data_science_image
    name: Build Variant Images
    runs-on: ubuntu-latest
    strategy:
      matrix:
       variant: [keras, pymc3, sklearn]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build docker image if it is not on registry
        run: make image_${{ matrix.variant }}
        
      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image to Docker hub Registry
        run: |
          IMAGE_ID=${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          # Strip git ref prefix from version
          VERSION=${{ matrix.variant }}

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          echo IMAGE_NAME=$IMAGE_NAME

          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME:$VERSION $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION